<?php

namespace ContainerRHNV1zW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NY2GYvVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NY2GYvV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NY2GYvV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AuthorController::Add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AuthorController::AddStatic' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AuthorController::edit' => ['privates', '.service_locator.678A05k', 'get_ServiceLocator_678A05kService', true],
            'App\\Controller\\AuthorController::read' => ['privates', '.service_locator.AkfJmMv', 'get_ServiceLocator_AkfJmMvService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AuthorController:Add' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AuthorController:AddStatic' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\AuthorController:edit' => ['privates', '.service_locator.678A05k', 'get_ServiceLocator_678A05kService', true],
            'App\\Controller\\AuthorController:read' => ['privates', '.service_locator.AkfJmMv', 'get_ServiceLocator_AkfJmMvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AuthorController::Add' => '?',
            'App\\Controller\\AuthorController::AddStatic' => '?',
            'App\\Controller\\AuthorController::edit' => '?',
            'App\\Controller\\AuthorController::read' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthorController:Add' => '?',
            'App\\Controller\\AuthorController:AddStatic' => '?',
            'App\\Controller\\AuthorController:edit' => '?',
            'App\\Controller\\AuthorController:read' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
