<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVCqYdhU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVCqYdhU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVCqYdhU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVCqYdhU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVCqYdhU\App_KernelDevDebugContainer([
    'container.build_hash' => 'VCqYdhU',
    'container.build_id' => '41891bd8',
    'container.build_time' => 1728662072,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVCqYdhU');
